apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employee-istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/istio-gitops.git'
    targetRevision: main
    path: istio-configs
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
